# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

on:
    push:
        paths:
            - "**.php"
            - ".github/workflows/*.yml"
        branches:
            - main
    pull_request:
        paths:
            - "**.php"
            - ".github/workflows/*.yml"

name: "Code style"

jobs:
    run:
        name: "Code Style"
        runs-on: ${{ matrix.operating-system }}
        strategy:
            fail-fast: false
            matrix:
                operating-system: [ubuntu-latest]
                php-versions: ["8.1"]

        steps:
            - name: Set git to use LF
              run: |
                  git config --global core.autocrlf false
                  git config --global core.eol lf

            - name: Checkout
              uses: actions/checkout@v4

            - name: Install PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-versions }}

            - name: Install dependencies
              uses: ramsey/composer-install@v2

            - name: Run Grumphp
              run: vendor/bin/grumphp run --testsuite=cs -n
